image: rikorose/gcc-cmake

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .

test:
  stage: test
  script:
    - ctest